CREATE_SUBDOMAINS_TABLE = """
CREATE TABLE subdomains (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subdomain VARCHAR(255) NOT NULL,
    registered_on DATE,
    detected_at VARCHAR(255) NOT NULL
);
"""

ALL_TABLES = [
    CREATE_SUBDOMAINS_TABLE
]